<?xml version="1.0"?>
<package format="3">
  <name>hikrobot_camera</name>
  <version>0.0.0</version>
  <description>ROS 2 Humble driver for Hikrobot industrial cameras based on the MVS SDK.</description>
  <maintainer email="redstore666@qq.com">李浩然</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>